import React from 'react';
import './Landing.css';

export default function Landing({ onStartAssessment, onBreedHealth }) {
  return <main className="landing">
    <nav className="landing-nav"><span className="logo">Canine<span>IQ</span></span><div className="nav-links"><button className="nav-link" onClick={onBreedHealth}>Breed health</button><button className="btn-primary" onClick={onStartAssessment}>Begin assessment</button></div></nav>
    <section className="hero">
      <div className="hero-copy"><p className="hero-eyebrow">A welfare intervention, not a personality quiz</p><h1>Want the dog.<br /><em>Ready for the life?</em></h1><p className="hero-sub">A dog is not a costume, a security system, or proof that you are a certain kind of person. CanineIQ asks whether you can provide the time, control, training, money, and patience your choice demands.</p><div className="hero-actions"><button className="btn-primary btn-large" onClick={onStartAssessment}>Find out before you commit <span aria-hidden="true">↗</span></button><button className="btn-ghost" onClick={onBreedHealth}>Understand the health burden</button></div></div>
      <div className="hero-dog glass"><img src="/images/pitbull.jpg" alt="Pit bull looking directly at the camera" /><div className="hero-dog-caption"><span>The breed is not the villain.</span><strong>Your choices decide whether this works.</strong></div><div className="hero-stamp">01<br /><small>THE REAL<br />QUESTION</small></div></div>
    </section>
    <section className="manifesto glass"><p className="section-label">We'll say it plainly</p><blockquote>If you choose a powerful or heavily bred dog because of how it looks, you also choose the work that keeps it healthy, contained, trained, and safe. When the image stops exciting you, the responsibility does not.</blockquote></section>
    <section className="cards-section"><div className="section-label">What we will not let you skip</div><div className="cards-grid"><article className="glass card"><span className="card-index">01</span><h2>The life you can provide</h2><p>We look at space, time, money, household safety, experience, and what happens when your week goes badly.</p></article><article className="glass card"><span className="card-index">02</span><h2>The reason you chose it</h2><p>Protection, status, rescue, health, companionship: the motivation changes the responsibility you are accepting.</p></article><article className="glass card"><span className="card-index">03</span><h2>The dog’s actual needs</h2><p>Not stereotypes. Not marketing. A plain-language account of the work this specific dog will need from you.</p></article><article className="glass card"><span className="card-index">04</span><h2>A decision you can act on</h2><p>You leave with clear next steps: what is working, what is missing, and whether you should wait before bringing a dog home.</p></article></div></section>
    <footer className="landing-footer"><span>CanineIQ — DEV Weekend Challenge: Dog Days Edition</span><a href="https://dev.to/challenges/weekend-2026-08-13" target="_blank" rel="noreferrer">Read the challenge brief ↗</a></footer>
  </main>;
}
