const BREED_TRAITS = {
  pitbull: { energy: 3, apartmentFriendly: 0, fragility: 0, grooming: 1, healthCost: 1, kidTolerance: 1, trainability: 2, hardMode: 1 },
  rottweiler: { energy: 2, apartmentFriendly: 0, fragility: 0, grooming: 1, healthCost: 1, kidTolerance: 0, trainability: 2, hardMode: 1 },
  german_shepherd: { energy: 3, apartmentFriendly: 0, fragility: 0, grooming: 2, healthCost: 2, kidTolerance: 1, trainability: 2, hardMode: 1 },
  husky: { energy: 3, apartmentFriendly: 0, fragility: 0, grooming: 2, healthCost: 1, kidTolerance: 1, trainability: 3, hardMode: 1 },
  labrador: { energy: 3, apartmentFriendly: 1, fragility: 0, grooming: 1, healthCost: 1, kidTolerance: 2, trainability: 1, hardMode: 0 },
  french_bulldog: { energy: 1, apartmentFriendly: 1, fragility: 0, grooming: 1, healthCost: 3, kidTolerance: 2, trainability: 1, hardMode: 0 },
  pug: { energy: 1, apartmentFriendly: 1, fragility: 0, grooming: 1, healthCost: 3, kidTolerance: 2, trainability: 1, hardMode: 0 },
  english_bulldog: { energy: 1, apartmentFriendly: 1, fragility: 0, grooming: 1, healthCost: 3, kidTolerance: 2, trainability: 2, hardMode: 0 },
  doberman: { energy: 3, apartmentFriendly: 0, fragility: 0, grooming: 1, healthCost: 2, kidTolerance: 0, trainability: 2, hardMode: 1 },
  border_collie: { energy: 3, apartmentFriendly: 0, fragility: 0, grooming: 2, healthCost: 1, kidTolerance: 1, trainability: 2, hardMode: 0 },
  beagle: { energy: 3, apartmentFriendly: 1, fragility: 0, grooming: 1, healthCost: 1, kidTolerance: 2, trainability: 2, hardMode: 0 },
  boxer: { energy: 3, apartmentFriendly: 0, fragility: 0, grooming: 1, healthCost: 2, kidTolerance: 2, trainability: 1, hardMode: 1 },
  chihuahua: { energy: 2, apartmentFriendly: 1, fragility: 1, grooming: 1, healthCost: 2, kidTolerance: -1, trainability: 2, hardMode: 0 },
  dalmatian: { energy: 3, apartmentFriendly: 0, fragility: 0, grooming: 1, healthCost: 1, kidTolerance: 1, trainability: 2, hardMode: 0 },
  dachshund: { energy: 2, apartmentFriendly: 1, fragility: 1, grooming: 1, healthCost: 3, kidTolerance: -1, trainability: 2, hardMode: 0 },
  samoyed: { energy: 3, apartmentFriendly: 0, fragility: 0, grooming: 3, healthCost: 1, kidTolerance: 2, trainability: 2, hardMode: 0 },
  akita: { energy: 2, apartmentFriendly: 0, fragility: 0, grooming: 2, healthCost: 2, kidTolerance: -1, trainability: 3, hardMode: 1 },
  chow_chow: { energy: 1, apartmentFriendly: 0, fragility: 0, grooming: 3, healthCost: 2, kidTolerance: -2, trainability: 3, hardMode: 1 },
  corgi: { energy: 3, apartmentFriendly: 0, fragility: 0, grooming: 2, healthCost: 1, kidTolerance: 1, trainability: 2, hardMode: 0 },
  eskimo_dog: { energy: 3, apartmentFriendly: 1, fragility: 0, grooming: 3, healthCost: 1, kidTolerance: 1, trainability: 2, hardMode: 0 },
  havanese: { energy: 2, apartmentFriendly: 1, fragility: 0, grooming: 2, healthCost: 1, kidTolerance: 1, trainability: 2, hardMode: 0 },
  malamute: { energy: 3, apartmentFriendly: 0, fragility: 0, grooming: 2, healthCost: 1, kidTolerance: 1, trainability: 3, hardMode: 1 },
  newfoundland: { energy: 2, apartmentFriendly: 0, fragility: 0, grooming: 3, healthCost: 2, kidTolerance: 2, trainability: 2, hardMode: 0 },
  papillon: { energy: 2, apartmentFriendly: 1, fragility: 1, grooming: 2, healthCost: 1, kidTolerance: 1, trainability: 1, hardMode: 0 },
  pekinese: { energy: 1, apartmentFriendly: 1, fragility: 1, grooming: 2, healthCost: 3, kidTolerance: -1, trainability: 3, hardMode: 0 },
  pomeranian: { energy: 2, apartmentFriendly: 1, fragility: 1, grooming: 3, healthCost: 1, kidTolerance: -1, trainability: 2, hardMode: 0 },
  poodle: { energy: 3, apartmentFriendly: 1, fragility: 0, grooming: 3, healthCost: 1, kidTolerance: 2, trainability: 1, hardMode: 0 },
  whippet: { energy: 2, apartmentFriendly: 1, fragility: 0, grooming: 1, healthCost: 1, kidTolerance: 1, trainability: 2, hardMode: 0 },
  weimaraner: { energy: 3, apartmentFriendly: 0, fragility: 0, grooming: 1, healthCost: 1, kidTolerance: 1, trainability: 2, hardMode: 1 },
  maltese: { energy: 1, apartmentFriendly: 1, fragility: 1, grooming: 3, healthCost: 1, kidTolerance: -1, trainability: 2, hardMode: 0 },
  shiba_inu: { energy: 2, apartmentFriendly: 1, fragility: 0, grooming: 2, healthCost: 1, kidTolerance: -1, trainability: 3, hardMode: 1 },
  bull_terrier: { energy: 3, apartmentFriendly: 1, fragility: 0, grooming: 1, healthCost: 2, kidTolerance: 2, trainability: 2, hardMode: 1 },
  miniature_pinscher: { energy: 2, apartmentFriendly: 1, fragility: 1, grooming: 1, healthCost: 1, kidTolerance: -1, trainability: 2, hardMode: 0 },
  puggle: { energy: 2, apartmentFriendly: 1, fragility: 0, grooming: 1, healthCost: 2, kidTolerance: 2, trainability: 1, hardMode: 0 },
  golden_retriever: { energy: 3, apartmentFriendly: 1, fragility: 0, grooming: 2, healthCost: 2, kidTolerance: 2, trainability: 1, hardMode: 0 },
  great_dane: { energy: 2, apartmentFriendly: 0, fragility: 0, grooming: 1, healthCost: 3, kidTolerance: 2, trainability: 2, hardMode: 0 },
  shih_tzu: { energy: 1, apartmentFriendly: 1, fragility: 1, grooming: 3, healthCost: 2, kidTolerance: 1, trainability: 2, hardMode: 0 },
  cocker_spaniel: { energy: 2, apartmentFriendly: 1, fragility: 0, grooming: 2, healthCost: 2, kidTolerance: 2, trainability: 2, hardMode: 0 },
  yorkshire_terrier: { energy: 2, apartmentFriendly: 1, fragility: 1, grooming: 3, healthCost: 2, kidTolerance: -1, trainability: 2, hardMode: 0 },
  west_highland: { energy: 2, apartmentFriendly: 1, fragility: 0, grooming: 2, healthCost: 2, kidTolerance: 1, trainability: 3, hardMode: 0 },
};

export default BREED_TRAITS;